export const I18N_CHAT_UI: Record<string, Record<string, string>> = {
  english: {
    selectModeOrReport: "Select Mode or Report",
    chooseGeneralOrDiscuss:
      "Choose general health mode or discuss a specific medical report",
    generalHealthChatNoDoc: "General Health Chat (No Document)",
    recentConversations: "Recent Conversations",
    onboardingSessionReadOnly: "Onboarding Session (Read-Only)",
    untitledSession: "Untitled Session",
    noReportsUploaded: "You haven't uploaded any medical reports yet.",
    uploadMedicalReport: "Upload Medical Report",
    seekImmediateAttention: "Seek immediate medical attention",
    emergencyWarning:
      "This may require urgent medical attention. Please contact emergency services or visit the nearest emergency department immediately.",
    onboardingArchive: "Onboarding Session (Read-Only Archive)",
    documentPrefix: "Document: ",
  },
  gujarati: {
    selectModeOrReport: "મોડ અથવા રિપોર્ટ પસંદ કરો",
    chooseGeneralOrDiscuss:
      "સામાન્ય સ્વાસ્થ્ય મોડ પસંદ કરો અથવા ચોક્કસ તબીબી અહેવાલ વિશે ચર્ચા કરો",
    generalHealthChatNoDoc: "સામાન્ય સ્વાસ્થ્ય ચર્ચા (કોઈ દસ્તાવેજ નથી)",
    recentConversations: "તાજેતરની વાતચીતો",
    onboardingSessionReadOnly: "ઓનબોર્ડિંગ સત્ર (ફક્ત વાંચવા માટે)",
    untitledSession: "શીર્ષક વગરનું સત્ર",
    noReportsUploaded: "તમે હજી સુધી કોઈ તબીબી અહેવાલો અપલોડ કર્યા નથી.",
    uploadMedicalReport: "તબીબી અહેવાલ અપલોડ કરો",
    seekImmediateAttention: "તાત્કાલિક તબીબી સારવાર મેળવો",
    emergencyWarning:
      "આ માટે તાત્કાલિક તબીબી સારવારની જરૂર પડી શકે છે. કૃપા કરીને તાત્કાલિક કટોકટી સેવાઓનો સંપર્ક કરો અથવા નજીકના કટોકટી વિભાગની મુલાકાત લો.",
    onboardingArchive: "ઓનબોર્ડિંગ સત્ર (ફક્ત વાંચવા માટેનું આર્કાઇવ)",
    documentPrefix: "દસ્તાવેજ: ",
  },
  hindi: {
    selectModeOrReport: "मोड या रिपोर्ट चुनें",
    chooseGeneralOrDiscuss:
      "सामान्य स्वास्थ्य मोड चुनें या किसी विशिष्ट मेडिकल रिपोर्ट पर चर्चा करें",
    generalHealthChatNoDoc: "सामान्य स्वास्थ्य चैट (कोई दस्तावेज़ नहीं)",
    recentConversations: "हाल की बातचीत",
    onboardingSessionReadOnly: "ऑनबोर्डिंग सत्र (केवल पढ़ने के लिए)",
    untitledSession: "बिना शीर्षक का सत्र",
    noReportsUploaded: "आपने अभी तक कोई मेडिकल रिपोर्ट अपलोड नहीं की है।",
    uploadMedicalReport: "मेडical रिपोर्ट अपलोड करें",
    seekImmediateAttention: "तुरंत चिकित्सा सहायता लें",
    emergencyWarning:
      "इसके लिए तत्काल चिकित्सा सहायता की आवश्यकता हो सकती है। कृपया तुरंत आपातकालीन सेवाओं से संपर्क करें या निकटतम आपातकालीन विभाग में जाएं।",
    onboardingArchive: "ऑनबोर्डिंग सत्र (केवल पढ़ने के लिए पुरालेख)",
    documentPrefix: "दस्तावेज़: ",
  },
  marathi: {
    selectModeOrReport: "મોડ અથવા રિપોર્ટ પસંદ કરો",
    chooseGeneralOrDiscuss:
      "સામાન્ય સ્વાસ્થ્ય મોડ પસંદ કરો અથવા ચોક્કસ તબીબી અહેવાલ વિશે ચર્ચા કરો",
    generalHealthChatNoDoc: "સામાન્ય સ્વાસ્થ્ય ચર્ચા (કોઈ દસ્તાવેજ નથી)",
    recentConversations: "તાજેતરની વાતચીતો",
    onboardingSessionReadOnly: "ઓનબોર્ડિંગ સત્ર (ફક્ત વાંચવા માટે)",
    untitledSession: "શીર્ષક વગરનું સત્ર",
    noReportsUploaded: "તમે હજી સુધી કોઈ તબીબી અહેવાલો અપલોડ કર્યા નથી.",
    uploadMedicalReport: "તબીબી અહેવાલ અપલોડ કરો",
    seekImmediateAttention: "તાત્કાલિક તબીબી સારવાર મેળવો",
    emergencyWarning:
      "આ માટે તાત્કાલિક તબીબી સારવારની જરૂર પડી શકે છે. કૃપા કરીને તાત્કાલિક કટોકટી સેવાઓનો સંપર્ક કરો અથવા નજીકના કટોકટી વિભાગની મુલાકાત લો.",
    onboardingArchive: "ઓનબોર્ડિંગ સત્ર (ફક્ત વાંચવા માટેનું આર્કાઇવ)",
    documentPrefix: "દસ્તાવેજ: ",
  },
  tamil: {
    selectModeOrReport: "முறை அல்லது அறிக்கையைத் தேர்ந்தெடுக்கவும்",
    chooseGeneralOrDiscuss:
      "பொது சுகாதார முறையைத் தேர்ந்தெடுக்கவும் அல்லது குறிப்பிட்ட மருத்துவ அறிக்கையைப் பற்றி விவாதிக்கவும்",
    generalHealthChatNoDoc: "பொது சுகாதார அரட்டை (ஆவணம் இல்லை)",
    recentConversations: "சமீபத்திய உரையாடல்கள்",
    onboardingSessionReadOnly: "உள்வாங்கல் அமர்வு (படிக்க மட்டும்)",
    untitledSession: "தலைப்பில்லா அமர்வு",
    noReportsUploaded:
      "நீங்கள் இன்னும் மருத்துவ அறிக்கைகள் எதையும் பதிவேற்றவில்லை.",
    uploadMedicalReport: "மருத்துவ அறிக்கையைப் பதிவேற்றவும்",
    seekImmediateAttention: "உடனடி மருத்துவ உதவியை நாடுங்கள்",
    emergencyWarning:
      "இதற்கு அவசர மருத்துவ உதவி தேவைப்படலாம். அவசர சேவைகளைத் தொடர்பு கொள்ளவும் அல்லது உடனடியாக அருகிலுள்ள அவசர சிகிச்சைப் பிரிவுக்குச் செல்லவும்.",
    onboardingArchive: "உள்வாங்கல் அமர்வு (படிக்க மட்டும் காப்பகம்)",
    documentPrefix: "ஆவணம்: ",
  },
};

export const SUGGESTED_QUESTIONS_I18N: Record<
  string,
  { general: string[]; document: string[] }
> = {
  english: {
    general: [
      "What are symptoms of diabetes?",
      "Reduce cholesterol levels",
      "Healthy blood pressure diet",
      "General heart health advice",
    ],
    document: [
      "What does my report mean?",
      "Are there any abnormal values?",
      "What should I discuss with my doctor?",
      "Can you explain this report in simple language?",
    ],
  },
  gujarati: {
    general: [
      "ડાયાબિટીસના લક્ષણો શું છે?",
      "કોલેસ્ટરોલનું સ્તર ઓછું કરો",
      "સ્વસ્થ બ્લડ પ્રેશર માટે આહાર",
      "સામાન્ય હૃદયના સ્વાસ્થ્ય અંગે સલાહ",
    ],
    document: [
      "મારા રિપોર્ટનો અર્થ શું છે?",
      "શું કોઈ અસામાન્ય મૂલ્યો છે?",
      "મારે મારા ડૉક્ટર સાથે શું ચર્ચા કરવી જોઈએ?",
      "શું તમે આ રિપોર્ટ સરળ ભાષામાં સમજાવી શકો છો?",
    ],
  },
  hindi: {
    general: [
      "मधुमेह के लक्षण क्या हैं?",
      "कोलेस्ट्रॉल का स्तर कम करें",
      "स्वस्थ रक्तचाप के लिए आहार",
      "सामान्य हृदय स्वास्थ्य सलाह",
    ],
    document: [
      "मेरी रिपोर्ट का क्या मतलब है?",
      "क्या कोई असामान्य मूल्य हैं?",
      "मुझे अपने डॉक्टर से क्या चर्चा करनी चाहिए?",
      "क्या आप इस रिपोर्ट को सरल भाषा में समझा सकते हैं?",
    ],
  },
  marathi: {
    general: [
      "मधुमेहाची लक्षणे काय आहेत?",
      "कोलेस्ट्रॉलची पातळी कमी करा",
      "निरोगी रक्तदाबासाठी आहार",
      "सामान्य हृदयाच्या आरोग्यासाठी सल्ला",
    ],
    document: [
      "माझ्या रिपोर्टचा अर्थ काय आहे?",
      "काही असामान्य मूल्ये आहेत का?",
      "मी माझ्या डॉक्टरांशी काय चर्चा करावी?",
      "तुम्ही हा रिपोर्ट सोप्या भाषेत समजावून सांगू शकता का?",
    ],
  },
  tamil: {
    general: [
      "நீரிழிவு நோயின் அறிகுறிகள் என்ன?",
      "கொழுப்பின் அளவை குறைக்கவும்",
      "ஆரோக்கியமான இரத்த அழுத்த உணவு",
      "பொதுவான இதய சுகாதார ஆலோசனை",
    ],
    document: [
      "எனது அறிக்கையின் அர்த்தம் என்ன?",
      "ஏதேனும் அசாதாரண மதிப்புகள் உள்ளதா?",
      "எனது மருத்துவரிடம் நான் என்ன விவாதிக்க வேண்டும்?",
      "இந்த அறிக்கையை எளிய மொழியில் விளக்க முடியுமா?",
    ],
  },
};

export const I18N_REPORT_CARD_UI: Record<string, Record<string, string>> = {
  english: {
    completed: "Completed",
    aiSummary: "AI Summary",
    showMore: "Show more",
    showLess: "Show less",
    keyFindings: "Key Findings",
    prescribedMedications: "Prescribed Medications",
    noFindingsYet: "No findings extracted yet — tap 'View Full Report' to check the original document.",
    viewFullReport: "View Full Report",
    askAiAboutReport: "ASK AI ABOUT THIS REPORT",
    medicalDisclaimer: "AI-extracted from your document. Please verify with the original report or your doctor.",
    prescription: "Prescription",
    medicalReport: "Medical Report",
    dose: "Dose",
    schedule: "Schedule",
    duration: "Duration",
    instructions: "Instructions",
    qty: "Qty",
    morning: "Morning",
    afternoon: "Afternoon",
    night: "Night",
    bedtime: "Bedtime",
    normal: "Normal",
    beforeFood: "Before Food",
    afterFood: "After Food",
    withFood: "With Food",
  },
  gujarati: {
    completed: "પૂર્ણ",
    aiSummary: "AI સારાંશ",
    showMore: "વધુ જુઓ",
    showLess: "ઓછું જુઓ",
    keyFindings: "મુખ્ય તારણો",
    prescribedMedications: "સૂચવેલ દવાઓ",
    noFindingsYet: "હજી સુધી કોઈ તારણો મળ્યા નથી — મૂળ દસ્તાવેજ તપાસવા માટે 'સંપૂર્ણ રિપોર્ટ જુઓ' પર ટેપ કરો.",
    viewFullReport: "સંપૂર્ણ રિપોર્ટ જુઓ",
    askAiAboutReport: "આ રિપોર્ટ વિશે AI ને પૂછો",
    medicalDisclaimer: "તમારા દસ્તાવેજમાંથી AI દ્વારા તારવેલ. કૃપા કરીને મૂળ રિપોર્ટ અથવા તમારા ડૉક્ટર સાથે ખાતરી કરો.",
    prescription: "પ્રિસ્ક્રિપ્શન",
    medicalReport: "તબીબી અહેવાલ",
    dose: "ડોઝ",
    schedule: "સમયપત્રક",
    duration: "સમયગાળો",
    instructions: "સૂચનાઓ",
    qty: "જથ્થો",
    morning: "સવાર",
    afternoon: "બપોર",
    night: "રાત",
    bedtime: "સૂવાના સમયે",
    normal: "સામાન્ય",
    beforeFood: "જમ્યા પહેલા",
    afterFood: "જમ્યા પછી",
    withFood: "ખોરાક સાથે",
  },
  hindi: {
    completed: "पूर्ण",
    aiSummary: "AI सारांश",
    showMore: "और देखें",
    showLess: "कम देखें",
    keyFindings: "मुख्य निष्कर्ष",
    prescribedMedications: "निर्धारित दवाएं",
    noFindingsYet: "अभी तक कोई निष्कर्ष नहीं मिला है — मूल दस्तावेज़ देखने के लिए 'पूरी रिपोर्ट देखें' पर टैप करें।",
    viewFullReport: "पूरी रिपोर्ट देखें",
    askAiAboutReport: "इस रिपोर्ट के बारे में AI से पूछें",
    medicalDisclaimer: "आपके दस्तावेज़ से AI द्वारा निकाला गया। कृपया मूल रिपोर्ट या अपने डॉक्टर से पुष्टि करें।",
    prescription: "पर्चा",
    medicalReport: "मेडिकल रिपोर्ट",
    dose: "खुराक",
    schedule: "समय",
    duration: "अवधि",
    instructions: "निर्देश",
    qty: "मात्रा",
    morning: "सुबह",
    afternoon: "दोपहर",
    night: "रात",
    bedtime: "सोते समय",
    normal: "सामान्य",
    beforeFood: "खाने से पहले",
    afterFood: "खाने के बाद",
    withFood: "खाने के साथ",
  },
  marathi: {
    completed: "पूर्ण",
    aiSummary: "AI सारांश",
    showMore: "अधिक पहा",
    showLess: "कमी पहा",
    keyFindings: "महत्वाचे निष्कर्ष",
    prescribedMedications: "दिलेली औषधे",
    noFindingsYet: "अद्याप कोणतेही निष्कर्ष सापडले नाहीत — मूळ दस्तऐवज तपासण्यासाठी 'पूर्ण अहवाल पहा' वर टॅप करा.",
    viewFullReport: "पूर्ण अहवाल पहा",
    askAiAboutReport: "या अहवालाबद्दल AI ला विचारा",
    medicalDisclaimer: "तुमच्या दस्तऐवजातून AI द्वारे काढलेले. कृपया मूळ अहवाल किंवा तुमच्या डॉक्टरांशी पडताळणी करा.",
    prescription: "प्रिस्क्रिप्शन",
    medicalReport: "वैद्यकीय अहवाल",
    dose: "डोस",
    schedule: "वेळापत्रक",
    duration: "कालावधी",
    instructions: "सूचना",
    qty: "प्रमाण",
    morning: "सकाळ",
    afternoon: "दुपार",
    night: "रात्र",
    bedtime: "झोपताना",
    normal: "सामान्य",
    beforeFood: "जेवणापूर्वी",
    afterFood: "जेवणानंतर",
    withFood: "जेवणासोबत",
  },
  tamil: {
    completed: "முடிந்தது",
    aiSummary: "AI சுருக்கம்",
    showMore: "மேலும் பார்க்க",
    showLess: "குறைவாக பார்க்க",
    keyFindings: "முக்கிய கண்டுபிடிப்புகள்",
    prescribedMedications: "பரிந்துரைக்கப்பட்ட மருந்துகள்",
    noFindingsYet: "இன்னும் விவரங்கள் கிடைக்கவில்லை — அசல் ஆவணத்தைப் பார்க்க 'முழு அறிக்கையைக் காண்க' என்பதைத் தட்டவும்.",
    viewFullReport: "முழு அறிக்கையைக் காண்க",
    askAiAboutReport: "இந்த அறிக்கையைப் பற்றி AI-யிடம் கேளுங்கள்",
    medicalDisclaimer: "உங்கள் ஆவணத்திலிருந்து AI பிரித்தெடுத்தது. தயவுசெய்து அசல் அறிக்கை அல்லது உங்கள் மருத்துவரிடம் சரிபார்க்கவும்.",
    prescription: "மருந்துச்சீட்டு",
    medicalReport: "மருத்துவ அறிக்கை",
    dose: "அளவு",
    schedule: "நேரம்",
    duration: "கால அளவு",
    instructions: "வழிமுறைகள்",
    qty: "அளவு",
    morning: "காலை",
    afternoon: "மதியம்",
    night: "இரவு",
    bedtime: "படுக்கைக்கு முன்",
    normal: "இயல்பான",
    beforeFood: "உணவுக்கு முன்",
    afterFood: "உணவுக்குப் பின்",
    withFood: "உணவுடன்",
  },
};

// Aliases for 2-letter language codes
I18N_REPORT_CARD_UI.en = I18N_REPORT_CARD_UI.english;
I18N_REPORT_CARD_UI.gu = I18N_REPORT_CARD_UI.gujarati;
I18N_REPORT_CARD_UI.hi = I18N_REPORT_CARD_UI.hindi;
I18N_REPORT_CARD_UI.mr = I18N_REPORT_CARD_UI.marathi;
I18N_REPORT_CARD_UI.ta = I18N_REPORT_CARD_UI.tamil;

SUGGESTED_QUESTIONS_I18N.en = SUGGESTED_QUESTIONS_I18N.english;
SUGGESTED_QUESTIONS_I18N.gu = SUGGESTED_QUESTIONS_I18N.gujarati;
SUGGESTED_QUESTIONS_I18N.hi = SUGGESTED_QUESTIONS_I18N.hindi;
SUGGESTED_QUESTIONS_I18N.mr = SUGGESTED_QUESTIONS_I18N.marathi;
SUGGESTED_QUESTIONS_I18N.ta = SUGGESTED_QUESTIONS_I18N.tamil;

