export type SupportedLanguage =
  | "english"
  | "hindi"
  | "gujarati"
  | "tamil"
  | "marathi";

export type SupportedLanguageCode = "en" | "hi" | "gu" | "ta" | "mr";

export type PreferredLanguageInput =
  | SupportedLanguage
  | SupportedLanguageCode
  | "English"
  | "Hindi"
  | "Gujarati"
  | "Tamil"
  | "Marathi"
  | string
  | null
  | undefined;

export interface AppConstants {
  // Common / Actions
  appName: string;
  save: string;
  cancel: string;
  edit: string;
  delete: string;
  add: string;
  update: string;
  retry: string;
  confirm: string;
  back: string;
  next: string;
  skip: string;
  continue: string;
  done: string;
  close: string;
  search: string;
  select: string;
  view: string;
  loading: string;
  processing: string;
  submit: string;
  clear: string;
  share: string;
  download: string;
  upload: string;
  yes: string;
  no: string;
  ok: string;
  success: string;
  error: string;
  warning: string;
  info: string;
  on: string;
  off: string;
  none: string;
  all: string;
  showAll: string;
  hideAll: string;
  today: string;
  yesterday: string;
  tomorrow: string;
  home: string;
  myProfile: string;

  // Auth & Account
  login: string;
  signup: string;
  logout: string;
  email: string;
  password: string;
  confirmPassword: string;
  forgotPassword: string;
  resetPassword: string;
  verifyOtp: string;
  enterOtp: string;
  resendOtp: string;
  mobile: string;
  phoneNumber: string;
  deleteAccount: string;
  logOutConfirm: string;
  deleteAccountConfirm: string;
  welcomeBack: string;
  getStarted: string;

  // Profile / Patient
  profile: string;
  editProfile: string;
  personalInfo: string;
  contactInfo: string;
  moreDetails: string;
  emailAddress: string;
  mobileNumber: string;
  firstName: string;
  lastName: string;
  fullName: string;
  enterFirstName: string;
  enterLastName: string;
  enterEmailAddress: string;
  enterMobileNumber: string;
  enterBloodGroup: string;
  dateOfBirth: string;
  age: string;
  gender: string;
  male: string;
  female: string;
  other: string;
  bloodGroup: string;
  allergies: string;
  knownAllergies: string;
  preferredLanguage: string;
  selectLanguage: string;
  saveDetails: string;
  verifyInformation: string;
  confirmProfileDetails: string;

  // Documents & Vault
  documents: string;
  vault: string;
  medicalRecords: string;
  medicalReports: string;
  uploadDocument: string;
  uploadReport: string;
  scanDocument: string;
  chooseFile: string;
  takePhoto: string;
  selectFromGallery: string;
  documentDetails: string;
  documentType: string;
  documentUploaded: string;
  deleteDocument: string;
  deleteDocumentConfirm: string;
  shareDocument: string;
  analyzingDocument: string;
  extractingText: string;
  noDocumentsFound: string;
  invalidDocument: string;
  documentProcessed: string;

  // Medications
  medications: string;
  medicationList: string;
  addMedication: string;
  editMedication: string;
  deleteMedication: string;
  deleteMedicationConfirm: string;
  deleteSelectedMedications: string;
  medicineName: string;
  medicineType: string;
  dosage: string;
  dosePerIntake: string;
  frequency: string;
  intakeFrequency: string;
  schedule: string;
  intakeSchedule: string;
  timing: string;
  startDate: string;
  endDate: string;
  ongoing: string;
  prescribedBy: string;
  specialInstructions: string;
  notes: string;
  refillAlert: string;
  totalQuantity: string;
  foodFrequency: string;
  beforeFood: string;
  afterFood: string;
  withFood: string;
  morning: string;
  noon: string;
  evening: string;
  night: string;
  customTime: string;

  // Medicine Types & Units
  tablet: string;
  capsule: string;
  syrup: string;
  injection: string;
  drops: string;
  spray: string;
  inhaler: string;
  ointment: string;
  patch: string;
  puff: string;
  ml: string;
  tsp: string;
  tbsp: string;

  // Frequency Options
  onceDaily: string;
  twiceDaily: string;
  thriceDaily: string;
  fourTimesDaily: string;
  asNeeded: string;

  // Reminders
  reminders: string;
  medicationReminders: string;
  upcomingReminders: string;
  completedReminders: string;
  pending: string;
  completed: string;
  overdue: string;
  markAsTaken: string;
  taken: string;
  missed: string;
  skipped: string;
  snooze: string;
  remindMeLater: string;
  refillReminder: string;
  filter: string;

  // Chat & AI Assistant
  chat: string;
  aiAssistant: string;
  healthAssistant: string;
  askAi: string;
  typeMessage: string;
  analyzingReport: string;
  medicinesExtracted: string;
  reviewExtracted: string;
  conflictResolution: string;
  duplicateDetected: string;
  keepExisting: string;
  replace: string;
  merge: string;
  discardNew: string;
  medicinesAddedSuccess: string;

  // Common Allergies
  penicillin: string;
  aspirin: string;
  ibuprofen: string;
  dust: string;
  pollen: string;
  peanuts: string;
  shellfish: string;
  latex: string;

  // Notifications & Messages
  notifications: string;
  noNotifications: string;
  markAllAsRead: string;

  // Errors & Status Messages
  networkError: string;
  serverError: string;
  connectionTimeout: string;
  somethingWentWrong: string;
  tryAgainLater: string;
  fileTooLarge: string;
  unsupportedFileType: string;
  oops: string;
  successTitle: string;
  errorTitle: string;
  loadingAssistant: string;
  preparingSecureConnection: string;
  connectionFailed: string;
  pleaseUploadDocsToGetStarted: string;
  noMedicationsFound: string;
  pleaseAddMedsToGetStarted: string;
  noMedicinesFound: string;
  noMedicinesFoundDesc: string;
  backToDashboard: string;
  drHealthAi: string;
  localMedicalAssistant: string;
  chatWelcomeIntro: string;
  analyzeDocuments: string;
  analyzeDocumentsDesc: string;
  secureAndLocal: string;
  secureAndLocalDesc: string;
  generalGuidance: string;
  generalGuidanceDesc: string;
  connecting: string;
  youreOnline: string;
  youreOffline: string;
  processingFailed: string;
  processingComplete: string;
  processingDocument: string;
  documentAnalysisError: string;
  extractingDocumentInfo: string;
  pleaseWaitMoment: string;

  // Screen-Specific: About & Info
  aboutUs: string;
  aboutTagline: string;
  ourMission: string;
  vision: string;
  visionDescription: string;
  privacyFirst: string;
  privacyFirstDescription: string;
  ourProjects: string;
  healthAI: string;
  familyVault: string;
  getInTouch: string;
  emailUs: string;
  website: string;
  privacyPolicy: string;
  termsOfService: string;
  version: string;
  comingSoon: string;
  beta: string;

  // Screen-Specific: Notifications
  unread: string;
  stayTunedForUpdates: string;
  noNotificationsFound: string;
  clearAll: string;

  // Screen-Specific: Home
  goodMorning: string;
  goodAfternoon: string;
  goodEvening: string;
  healthVaultWelcomesYou: string;
  healthVaultSummary: string;
  completeHealthInsights: string;
  quickActions: string;
  uploadDocSub: string;
  addMedSub: string;
  askAiSub: string;
  todaysReminders: string;
  viewAll: string;
  noRemindersToday: string;
  myVault: string;
  totalDocuments: string;
  recentDocuments: string;
  activeMedications: string;
  allSetForToday: string;

  // Screen-Specific: Auth
  loginTitle: string;
  loginSubtitle: string;
  enterMobile: string;
  getOtp: string;
  orContinueWith: string;
  google: string;
  facebook: string;
  microsoft: string;
  apple: string;
  byContinuingYouAgree: string;
  verifyMobile: string;
  enterCodeSentTo: string;
  didntReceiveCode: string;
  resendCodeIn: string;
  seconds: string;
  verifyAndProceed: string;
  resetPasswordTitle: string;
  newPassword: string;
  createPassword: string;

  // Screen-Specific: Documents & Vault
  myDocuments: string;
  familyMembers: string;
  manage: string;
  you: string;
  me: string;
  selected: string;
  featureImplementedSoon: string;
  limitExceeded: string;
  selectUpTo5Docs: string;
  processingInProgress: string;
  processingInProgressDesc: string;
  sortDocuments: string;
  chooseHowToOrder: string;
  newestFirst: string;
  recentlyAddedItems: string;
  oldestFirst: string;
  earliestAddedItems: string;
  aToZ: string;
  alphabeticalAscending: string;
  zToA: string;
  alphabeticalDescending: string;
  prescription: string;
  labReport: string;
  imagingReport: string;
  dischargeSummary: string;
  consultationReport: string;
  surgeryReport: string;
  vaccinationReport: string;
  medicalCertificate: string;
  otherMedicalDocument: string;
  unableToLoadDocuments: string;
  errorDisplayingDocuments: string;
  allDocuments: string;
  filterAndSort: string;
  sortByDate: string;
  sortByName: string;
  uploadingFiles: string;
  processingFiles: string;
  documentSummary: string;
  keyFindings: string;
  extractedData: string;
  diagnosis: string;
  prescriptions: string;
  labResults: string;
  saveToVault: string;
  editDocumentTitle: string;
  documentName: string;
  documentCategory: string;
  selectCategory: string;
  notesOptional: string;
  filePreview: string;
  shareWithDoctor: string;
  shareLink: string;
  sharedWith: string;

  // Screen-Specific: Medications
  activeMeds: string;
  completedMeds: string;
  noMedications: string;
  searchMedicines: string;
  searchMedications: string;
  medicine: string;
  medicines: string;
  medication: string;
  addMedicineTitle: string;
  editMedicineTitle: string;
  medicineDetails: string;
  refillDetails: string;
  refillNow: string;
  refillQuantity: string;
  daysSupply: string;
  instructions: string;
  prescribingDoctor: string;
  reminderTimes: string;
  dosageInformation: string;
  conflictWarning: string;
  duplicateMedicine: string;
  keepBoth: string;
  replaceExisting: string;
  reviewAll: string;
  saveMedication: string;
  saving: string;
  addAndContinue: string;
  added: string;
  review: string;
  refill: string;
  selectMedications: string;
  selectAll: string;
  deselectAll: string;
  sortMedications: string;
  chooseOrderItems: string;
  tipLongPressSelectMultiple: string;
  thisMayTakeAWhile: string;
  nameIsRequired: string;
  unitIsRequired: string;
  totalQuantityRequired: string;
  selectExactReminderTimes: string;
  drop: string;
  maintainMedicalSchedule: string;
  reviewMedications: string;
  readyToSave: string;
  addedAddAnother: string;
  existingMedication: string;
  incomingNewMedication: string;
  doctor: string;
  dose: string;
  start: string;
  qty: string;
  hideDetails: string;
  viewMoreDetails: string;
  remove: string;
  addAnotherMedicine: string;
  savingMedications: string;
  type: string;
  noAllergiesAdded: string;
  saveProfile: string;
  savingProfile: string;
  tapToAddAllergies: string;
  tapCameraToChangePhoto: string;
  reset: string;
  apply: string;
  refillMedication: string;
  refillMedicationDesc: string;
  remainingPills: string;
  pillsLeft: string;
  addPillsToRefill: string;
  enterPillsToAdd: string;
  enterNumberOfPills: string;
  pills: string;
  refillInfoNote: string;
  day: string;
  days: string;

  // Screen-Specific: Reminders
  todaySchedule: string;
  upcomingSchedule: string;
  allReminders: string;
  noReminders: string;
  takeMedicine: string;
  skipMedicine: string;
  markCompleted: string;
  refillAlerts: string;
  dailyReminders: string;
  stayOnTrackReminders: string;
  tasksCompleted: string;
  requiresAttention: string;
  filterReminders: string;
  narrowDownReminders: string;
  byMedicationType: string;
  byCustomDate: string;
  noRemindersFound: string;
  noRemindersAtTheMoment: string;
  overdueReminders: string;
  pendingReminders: string;
  completedLate: string;
  dueIn: string;
  completedAtLabel: string;
  lateBy: string;
  scheduledAt: string;
  markComplete: string;
  completeNow: string;
  actionAvailableAt: string;
  timeUnknown: string;

  // Screen-Specific: Chat
  chatHealthAssistant: string;
  suggestedTopics: string;
  clearChat: string;
  newSession: string;
  viewDocument: string;
  listening: string;
  messageDrHealth: string;
  voicePermissionDenied: string;
  voiceInputUnavailable: string;
  symptomOfDiabetes: string;
  reduceCholesterol: string;
  healthyBpDiet: string;
  generalHeartHealth: string;
  whatReportMeans: string;
  abnormalValues: string;
  discussWithDoctor: string;
  explainReportSimple: string;

  // Screen-Specific: Document Upload BottomSheet & Modal
  addDocument: string;
  addDocumentSubtitle: string;
  camera: string;
  gallery: string;
  files: string;
  selectedDocuments: string;
  uploadFiles: string;
  uploadingDocuments: string;
  editDocument: string;
  editDocumentSubtitle: string;
  documentPreview: string;
  pdfDocument: string;
  originalFileName: string;
  enterDocumentName: string;
  documentNameCannotBeEmpty: string;
  discard: string;
  singleDocumentProcessingWait: string;
  documentsProcessingWait: string;
  maxFiveDocumentsAllowed: string;
  failedToPickDocuments: string;
  failedToPickImages: string;
  permissionDenied: string;
  cameraPermissionRequired: string;
  enableCameraFromSettings: string;

  // Allow flexible index access like constant?.[text]
  [key: string]: string | undefined;
}
