import type { MedicalDocument } from "../types";

export const generateProfessionalEmail = (doc: MedicalDocument) => {
  const dateStr = new Date(doc.createdAt).toLocaleDateString();

  return `
Dear Health Professional / Recipient,

I am sharing a summary of a medical document. 

--- DOCUMENT OVERVIEW ---
Record Title: ${doc.title}
Date of Record: ${dateStr}
Document Type: ${doc.category || "General Medical"}

--- AI-GENERATED SUMMARY ---
${doc.AISummary}

Please find the original document image attached to this email for your reference.

Best regards,
[User Name]

---------------------------------------------------------
DISCLAIMER: This summary was generated by an AI assistant. It is intended for informational purposes only and should not replace professional medical advice, diagnosis, or treatment. Please review the attached original document for clinical accuracy.
  `.trim();
};
